base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='homepage'),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import (
    create_order,
    delete_order,
    order_list,
    order_detail,
)


app_name = 'orders'
urlpatterns = [
    path('new-order/<int:pk>/', create_order, name='create'),
    path('delete/<int:pk>/', delete_order, name='delete'),
    path('order-list/', order_list, name='list'),
    path('<int:pk>/', order_detail, name='detail'),
]

orders/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from products.models import Product

STATUS = (
    ("CREATED", "Created"),
    ("IN_PROCESS", "In Process"),
    ("SUCCESS", "Success"),
)


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    products = models.ForeignKey(Product, on_delete=models.CASCADE)

    address = models.CharField(max_length=80)
    quantity = models.IntegerField(default=0)
    total_price = models.DecimalField(max_digits=12, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS, default="CREATED")
    date_created = models.DateField(auto_now_add=True)

    # Show order id on admin page
    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse("orders:detail", kwargs={"pk": self.pk})

orders/forms.py
from django import forms


class CreateOrderForm(forms.Form):
    address = forms.CharField(
        label="<strong> Address </strong>",
        widget=forms.TextInput(attrs={'placeholder': "Where can we ship this item to you?"}),
    )
    quantity = forms.IntegerField(
        label="<strong> Quantity </strong>",
        widget=forms.TextInput(attrs={'placeholder': 'How much do you want to buy?'}),
    )

    def __init__(self, *args, **kwargs):
        product = kwargs.pop("products") or None
        super().__init__(*args, **kwargs)
        # Get the product so we can modify it in clean method
        self.products = product

    def clean_quantity(self):
        product = self.products
        quantity = self.cleaned_data.get("quantity")
        print(product.price)
        print(quantity)
        if not isinstance(quantity, int):
            raise forms.ValidationError("Please enter the correct number")
        if quantity <= 0:
            raise forms.ValidationError("Please enter the correct number")
        if not product.available():
            raise forms.ValidationError("Sorry this item is out of stock, please try again later...")
        if quantity > product.stock:
            raise forms.ValidationError("Sorry this item only has " + str(product.stock) + " pieces left")
        if product.price * quantity >= 9999999999:
            raise forms.ValidationError("Sorry your order is very expensive, try to separate it into 2 or more orders. Thanks")
        return quantity

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import CreateOrderForm
from products.models import Product
from .models import Order


@login_required(login_url='accounts:login')
def create_order(request, pk):
    product = get_object_or_404(Product, id=pk)
    form = CreateOrderForm(request.POST or None, products=product)
    if form.is_valid():
        user = request.user
        products = product
        address = form.cleaned_data.get('address')
        quantity = form.cleaned_data.get('quantity')
        Order.objects.create(
            user=user,
            products=products,
            address=address,
            quantity=quantity,
            total_price=quantity*product.price
        )
        product.reduce_stock(quantity)
        product.save()
        return redirect('orders:list')
    context = {
        "form": form,
        "product": product,
    }
    return render(request, "orders/create_order.html", context)


@login_required(login_url='accounts:login')
def delete_order(request, pk):
    order = get_object_or_404(Order, id=pk)
    order.delete()
    return redirect('orders:list')


@login_required(login_url='accounts:login')
def order_list(request):
    order_list = Order.objects.filter(user=request.user)
    return render(request, "orders/order_list.html", {"order_list": order_list})


@login_required(login_url='accounts:login')
def order_detail(request, pk):
    order = get_object_or_404(Order, id=pk)
    return render(request, "orders/order_detail.html", {"order": order})

orders/templates/orders/create_order.html
{% extends 'base.html' %}
{% load humanize %}  <!-- Formatting product price (ex: 12,300) -->
{% load crispy_forms_tags %}

{% block content %}
<div class="row align-items-center">
    <div class="col align-self-center p-3">
        <h2 class="fw-bold">{{ product.name }}</h2>
        <h4><span class="badge bg-success">${{ product.price|intcomma }}</span></h4>
        <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <p>Available : {{ product.stock }} pcs</p>
            <input class="btn btn-primary" type="submit" value="Buy">
        </form>
        </div>
    </div>
</div>
{% endblock content %}

orders/templates/orders/order_detail.html
{% extends 'base.html' %}
{% load humanize %}  <!-- Formatting product price (ex: 12,300) -->

{% block content %}
    <div class="card">
        <h4 class="card-header p-3 fw-bold">Order ID : {{ order.id }}</h4>
        <div class="card-body p-0">
        <h5 class="card-title p-3">Thanks for your order, {{ order.user }}</h5>
        <p class="card-text"><pre>
    Product     : {{ order.products }} <br>
    Quantity    : {{ order.quantity }} <br>
    Status      : {{ order.status }} <br>
    Date        : {{ order.date_created }} <br>
    Address     : {{ order.address }} <br><br>
    <b>Total Price : ${{ order.total_price|intcomma }} </b></pre></p>
        {% if order.status == "CREATED" %}
        <div class="d-grid gap-2 d-sm-block p-3 ms-3">
            <!-- Button trigger modal -->
            <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Cancel Order</a>
        </div>
        {% endif %}
    </div>

    <!-- Modal to call delete order function -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cancel Order</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to cancel this order?
            </div>
            <div class="modal-footer">
                <a class="btn btn-danger" href="{% url 'orders:delete' order.id %}">Cancel Order</a>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

orders/templates/orders/order_list.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-group">
{% for order in order_list %}
    {% if order.status != "SUCCESS" %}
        <li class="list-group-item">
            <div class="ms-2">
                <div class="fw-bold fs-6"><a href="{{ order.get_absolute_url }}">Order ID : {{ order.id }}</a></div>
                <div class="d-flex my-2">
                    <h6 class="fw-bold">{{ order.products }}
                    <span class="badge bg-info mx-2">{{ order.quantity }} pcs</span>
                    <span class="badge bg-success">{{ order.status }}</span>
                    </h6>
                </div>
            </div>
        </li>
    {% endif %}
{% endfor %}
</ul>
{% endblock content %}