base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='homepage'),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import (
    create_order,
    delete_order,
    order_list,
    order_detail,
)


app_name = 'orders'
urlpatterns = [
    path('new-order/<int:pk>/', create_order, name='create'),
    path('delete/<int:pk>/', delete_order, name='delete'),
    path('order-list/', order_list, name='list'),
    path('<int:pk>/', order_detail, name='detail'),
]

products/urls.py
from django.urls import path

from .views import product_detail


app_name = 'products'
urlpatterns = [
    path('<int:pk>/', product_detail, name='detail'),
]

products/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    # Show category name on admin page
    def __str__(self):
        return self.name


class Product(models.Model):
    # order = models.ManyToManyField(Order)

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    date_created = models.DateField(auto_now_add=True)
    stock = models.IntegerField(default=0)
    category = models.ManyToManyField(Category, blank=True)
    image = models.ImageField(upload_to='products/')  # automatically upload to MEDIA_ROOT/products/

    def available(self):
        return self.stock > 0

    def reduce_stock(self, quantity):
        self.stock -= quantity
        return self.stock

    # Show product name on admin page
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"pk": self.pk})

products/views.py
from django.shortcuts import render, get_object_or_404

from .models import Product, Category


# Views for base.html
def navbar(request):
    # Get all category from Category Table
    category_list = Category.objects.all()
    return {'category_list': category_list}


def homepage(request):
    product_list = []
    # Get all available product
    for product in Product.objects.all():
        if product.available():
            product_list.append(product)
    context = {'product_list': product_list}
    return render(request, 'products/homepage.html', context)


def product_detail(request, pk):
    product = get_object_or_404(Product, id=pk)
    context = {'product': product}
    return render(request, 'products/product_detail.html', context)

products/templates/products/homepage.html
{% extends 'base.html' %}
{% load humanize %}  <!-- Formatting product price (ex: 12,300) -->

{% block content %}
    <div class="row">
        {% for product in product_list %}
        <div class="col-xxl-2 col-xl-3 col-lg-4 col-md-6 col-sm-6">
            <div class="card mt-3 bg-dark">
                <div class="card-img-top mt-5 text-center">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.image.url }}" style="height: 200px; width: 200px;">
                </a>
                </div>
                <div class="card-body text-light text-center">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <span class="badge bg-success">${{ product.price|intcomma }}</span><br>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load humanize %}  <!-- Formatting product price (ex: 12,300) -->

{% block content %}
<div class="row">
    <div class="d-flex justify-content-center col-xl-5 col-lg-12 p-5">
        <img src="{{ product.image.url }}" style="width: 400px; height: 400px; border: 2px solid lightgray;">
    </div>
    <div class="col-xl-7 col-lg-12 p-5">
        <h2 class="fw-bold">{{ product.name }}</h2>
        <h4><span class="badge bg-success">${{ product.price|intcomma }}</span></h4>
        <p>Description : {{ product.description }}</p>
        {% for category in product.category.all %}
            <span class="badge bg-info">{{ category }}</span>
        {% endfor %}
        <br><br>
        <a class="btn btn-primary" href="{% url 'orders:create' product.id %}">Create Order</a>
    </div>
</div>
{% endblock content %}